export const URL_CREATE_WORK_SHIFTS = '/home/work-shifts/create';
export const businessUnitsHomeUrl = '/home/business-units';
export const URL_SUCCESS_ONBOARDING =
  '/home/onboarding-activities?success=true';
export const URL_BACK_FORM_ONBOARDING = '/home/onboarding-activities';
export const URL_SUCCESS_CREATE_WSHIFTS =
  '/home/work-shifts/create?success=true';
export const URL_BACK_CREATE_WSHIFTS = '/home/work-shifts';
export const URL_SUCCESS_NO_SENT_EMAIL_CANDIDATE =
  '/home/candidates/create?success=created-no-sent-email';
export const URL_BACK_CREATE_CANDIDATE = '/home/candidates';
export const URL_DASHBOARD = '/dashboard';
export const URL_TUTORIALS = '/home/tutorials';
export const URL_POST_JOB = '/home/my-jobs/post-new-jobs';
export const URL_MY_JOBS = '/home/my-jobs';
export const URL_SUBMISSIONS = '/home/submissions';
export const URL_CONTRACTS = '/home/contracts';
export const URL_TYE = '/home/t&e';
export const URL_INVOICES = '/home/invoices';
export const URL_REPORTS = '/home/reports';
export const URL_SUPPLIERS = '/home/suppliers';
export const URL_BUYERS = '/home/buyers';
export const URL_CANDIDATES = '/home/candidates';
export const URL_APPROVALS = '/home/approvals';
export const URL_USERS = '/home/users';
export const URL_ONBOARDING_ITEMS = '/home/onboarding-activities';
export const URL_WORK_SHIFTS = '/home/work-shifts';
export const URL_BUSINESS_UNITS = '/home/business-units';
export const URL_GL_CODES = '/home/gl-codes';
export const URL_COST_CENTER = '/home/cost-centers';
export const URL_IMPORTS = '/home/imports';
export const URL_SETTINGS = '/home/settings';
export const URL_LOG_OUT = 'logout';
export const URL_CREATE_CANDIDATE = '/home/candidates/create';
export const URL_ERROR_404 = '/404';
export const URL_ERROR_500 = '/auth/server-down';
export const URL_JOBS_TO_APPROVE = '/home/job-approvals';
